name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build extension
        run: npm run build

      - name: Extract release notes
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///g')
          sed -n "/## \[$VERSION\]/,/## \[[0-9]*\.[0-9]*\.[0-9]*\]/p" CHANGELOG.md | perl -pe 'BEGIN{undef $/;} s/\n## \[[0-9]*\.[0-9]*\.[0-9]*\]\n/\n/sg' > RELEASE_NOTES.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: RELEASE_NOTES.md
          files: |
            *.vsix
          draft: false
          prerelease: false
        if: startsWith(github.ref, 'refs/tags/')
